site_name: Incident Bot Documentation
repo_url: https://github.com/incidentbot/incidentbot
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - content.code.copy
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - search.highlight
    - search.suggest
    - search.share
  palette:
    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - glightbox
  - search:
      lang: en
nav:
  - Home:
      - index.md
      - Installation: 'installation.md'
      - Configuration: 'configuration.md'
      - Integrations: 'integrations.md'
      - Features: 'features.md'
      - Web Interface: 'ui.md'
      - Usage Guide: 'usage.md'
      - FAQ: 'faq.md'
      - Changelog: 'changelog.md'
