apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: incidentbot-docs
  name: incidentbot-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incidentbot-docs
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: incidentbot-docs
    spec:
      containers:
        - name: incidentbot-docs
          image: eb129/incidentbot-docs
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: 200m
              memory: 128M
            requests:
              cpu: 100m
              memory: 64M
