apiVersion: v1
kind: Service
metadata:
  name: incidentbot-docs
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: incidentbot-docs
